#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : ktp-send-file
Version  : 18.12.2
Release  : 1
URL      : https://download.kde.org/stable/applications/18.12.2/src/ktp-send-file-18.12.2.tar.xz
Source0  : https://download.kde.org/stable/applications/18.12.2/src/ktp-send-file-18.12.2.tar.xz
Source99 : https://download.kde.org/stable/applications/18.12.2/src/ktp-send-file-18.12.2.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: ktp-send-file-bin = %{version}-%{release}
Requires: ktp-send-file-data = %{version}-%{release}
Requires: ktp-send-file-license = %{version}-%{release}
Requires: ktp-send-file-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : ktp-common-internals-dev
BuildRequires : qtbase-dev mesa-dev
BuildRequires : telepathy-qt-dev

%description
No detailed description available

%package bin
Summary: bin components for the ktp-send-file package.
Group: Binaries
Requires: ktp-send-file-data = %{version}-%{release}
Requires: ktp-send-file-license = %{version}-%{release}

%description bin
bin components for the ktp-send-file package.


%package data
Summary: data components for the ktp-send-file package.
Group: Data

%description data
data components for the ktp-send-file package.


%package license
Summary: license components for the ktp-send-file package.
Group: Default

%description license
license components for the ktp-send-file package.


%package locales
Summary: locales components for the ktp-send-file package.
Group: Default

%description locales
locales components for the ktp-send-file package.


%prep
%setup -q -n ktp-send-file-18.12.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557035725
mkdir -p clr-build
pushd clr-build
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1557035725
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ktp-send-file
cp COPYING %{buildroot}/usr/share/package-licenses/ktp-send-file/COPYING
pushd clr-build
%make_install
popd
%find_lang ktp-send-file

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ktp-send-file

%files data
%defattr(-,root,root,-)
/usr/share/kservices5/ServiceMenus/ktp-send-file.desktop

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ktp-send-file/COPYING

%files locales -f ktp-send-file.lang
%defattr(-,root,root,-)

